### ISSUE TITLE
居中的方式

### ISSUE THREAD

**Issue by ZUOZHE1997** [ZUOZHE1997/ZUOZHE1997.github.io#1]
<a name="P3n3Y"></a>
## flex布局的方法
这个是我常用的方法,一般现在布局我基本上用flex布局,然后辅助一些别的,常用的flex布局让元素居中的方法是

```css
    .parent{
        display: flex;/*Flex布局*/
        display: -webkit-flex; /* Safari */
        align-items: center;/*设置子元素在侧轴方向上的布局*/
    }

```
给父元素设置上之后,里面的子元素就可以了实现了,这种方法属于元素高度未知的情况下,点击[这里](https://www.runoob.com/w3cnote/flex-grammar.html)也可以看看flex布局的基本方法.

<a name="8fGgf"></a>
## 绝对定位 + translate 位移
translate:移动，是transform的一个方法,通过translate()方法，元素从其当前位置移动，根据给定的left(x坐标)和top(y坐标)位置参数：

```javascript
div {
        background-color: red;
        position: absolute;       绝对定位的盒子
        top: 50%;               首先，让上边线居中
        transform: translateY(-50%);    然后，利用translate，往上走自己宽度的一半【推荐写法】
    }
```
<a name="HTIBJ"></a>
## 
<a name="tb8H0"></a>
## 绝对定位 + margin:auto

```javascript
.element {
    position: absolute;
    left: 0; top: 0; right: 0; bottom: 0;
    margin: auto;    /* 有了这个就自动居中了 */
}
```
代码两个关键点：

- 上下左右均0位置定位；
- margin: auto

<a name="NtStV"></a>
## 行内元素
诸如文本啊等行内元素可以直接使用

```css
text-align: center;
```

来居中,**让文字的行高 等于 盒子的高度**，可以让单行文本垂直居中。

<a name="D1AIl"></a>
## 块级元素
给元素设置：（让当前元素在父亲里居中）
```css
//方式一
 	margin: auto;
	方式二
	margin: 0 auto;
```
上面的代码， `margin: auto`相当于`margin: auto auto auto auto`。`margin: 0 auto`相当于`margin: 0 auto 0 auto`，四个值分别对应上右下左。

- 垂直方向：根据规范，margin-top: auto 和 margin-bottom: auto，其计算值为0。
- 水平方向：水平方向的 auto，其计算值取决于可用空间（**剩余空间**）。
